version: "3.7"
services:
  #PHP
  app:
    build:
      args:
        user: deploy
        uid: 1000
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    restart: unless-stopped
    command: bash -c 'php artisan migrate'
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/logs/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app
      - database

  #Mysql
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33061:3306"
    restart: unless-stopped
    container_name: database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    # volumes:
    #   - ./.docker/mysql/data:/var/lib/mysql
    networks:
      - app-network

#Docker network
networks:
  app-network:
    driver: bridge
